### ISSUE TITLE
Monotonic timers can run backward

### ISSUE THREAD

**Issue by madscientist159** [openbmc/linux#142]
@amboar 

Found an interesting bug somewhere in the OpenBMC system, presumed to be the kernel: monotonic timers appear to be able to run **backward**!

For the Talos systems we have a GPIO wired up to a piezo buzzer to be able to produce short beeps.  When trying to create a software beep generation utility, the timers kept acting weird (massive jitter, on the order of seconds), but this was chalked up to the underpowered BMC CPU at the time.

However, busy waiting on the output of CLOCK_MONOTONIC_RAW yielded something far more interesting:

```
OVERRAN timer (wanted 500000, got 6513841645600526421, start: 6513841646057535338.4828071968854116287 end: 2046806223074218103.2130774092136435831)
OVERRAN timer (wanted 500000, got 6513841645640195121, start: 6513841646131186691.4828071968967436340 end: 2363136375515369591.2617480013752422519)
OVERRAN timer (wanted 500000, got 6513841645630465387, start: 6513841646231423169.4828071969057943084 end: 2793648770391593079.3006203519299866743)
OVERRAN timer (wanted 500000, got 6513841645626057624, start: 6513841646291207849.4828071969113320001 end: 3050422015793418359.3244045566768173175)
```

Note how the end times are _less_ than the start times.  This is in direct contradiction with the definition of CLOCK_MONOTONIC / CLOCK_MONOTONIC_RAW and could explain some other timer-related oddities we've seen on the BMC.

Code is here:

https://git.raptorcs.com/git/talos-skeleton/tree/softbeep/beep_obj.c

EDIT:

Here's another ridiculous example, in clear violation of the spec.  I don't know if we're catching the timer mid-reload or something else, but this will probably affect other parts of the system at some point:

```
OVERRAN timer (wanted 500000, got 42649026441361, start: 42649081893965.4828071968415843550 end: 243287069567231690.248407018476414666)
OVERRAN timer (wanted 500000, got 42649026355744, start: 42649088328794.4828071968422192762 end: 270924449677584074.275676676371785418)
OVERRAN timer (wanted 500000, got 42649026364552, start: 42649121528188.4828071968455400964 end: 413514761154602698.418304817920747210)
OVERRAN timer (wanted 500000, got 42649026459139, start: 42649126084066.4828071968460051429 end: 433082108169168586.438278413006939850)
OVERRAN timer (wanted 500000, got 42649026325522, start: 42649129653804.4828071968463487550 end: 448414016134457034.453036440327038666)
OVERRAN timer (wanted 500000, got 42649036464755, start: 42649171790935.4828071968515763914 end: 629391615726724810.677561714060830410)
OVERRAN timer (wanted 500000, got 42649084051987, start: 42649231095137.4828071968622655348 end: 884101223832102602.1136656927313372874)
```

**Comment by shenki** [comment]
Are you sure this is a kernel issue? I did notice a bunch of compiler warnings when building the tool.

Once fixing them I wasn't able to reproduce. Here's some example output:

```
./beep_obj 
OVERRAN timer (wanted 500000, got 1324283, start: 5965383.929866907 end: 5965383.931191190)
OVERRAN timer (wanted 500000, got 41248000, start: 5965383.959487069 end: 5965384.735069)
OVERRAN timer (wanted 500000, got 16393535, start: 5965384.21594463 end: 5965384.37987998)
```

**Comment by madscientist159** [comment]
@shenki Do you mind posting the fixes you applied?  I haven't had any time to look into this again but I do remember the timer problem showed up after the system was online for a while and it took a number of retries of the `beep` program to trigger the problem.
