### ISSUE TITLE
Detaching egress BPF program from cgroup failed: Invalid argument

### ISSUE THREAD

**Issue by gkeishin** [openbmc/linux#159]
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v2.3-250"
VERSION_ID="v2.3-250-ge5b3860"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v2.3-250"
BUILD_ID="v2.3"
```
Looks like new kernel config thing
```
root@witherspoon:~# uname -a
Linux witherspoon 4.18.5-b9bdffdd891707c4d6995fbc7118fdb9ea426c47 #1 Tue Sep 4 19:50:55 UTC 2018 armv6l GNU/Linux
root@witherspoon:~#
```

`Journald snippet`
```
Sep 05 16:43:41 witherspoon systemd[1]: Attaching egress BPF program to cgroup /sys/fs/cgroup/unified/system.slice/systemd-timedated.service failed: Invalid argument
Sep 05 16:43:44 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 05 16:45:01 witherspoon systemd[1]: Attaching egress BPF program to cgroup /sys/fs/cgroup/unified/system.slice/systemd-hostnamed.service failed: Invalid argument
Sep 05 16:51:45 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 05 16:51:50 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 05 16:55:04 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 05 16:56:51 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 05 17:22:11 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 05 17:22:12 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 05 17:22:18 witherspoon systemd[1]: Attaching egress BPF program to cgroup /sys/fs/cgroup/unified/system.slice/systemd-timedated.service failed: Invalid argument
Sep 05 17:23:14 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
```

**Comment by gkeishin** [comment]
This one is flooding the journald @shenki

**Comment by geissonator** [comment]
Found some reference to this in https://github.com/systemd/systemd/issues/7054   Maybe a kernel config type thing @shenki ?  This is making our journal's a mess with master.

**Comment by geissonator** [comment]
There was a fix made under https://github.com/systemd/systemd/pull/7481 in systemd but this went into v236 of systemd and we're currently running v237, so that patch did not seem to fix our issue.  The confusion seems to be systemd getting hints from the kernel that BPF is enabled but it's actually not.

**Comment by shenki** [comment]
We use eBPF for debugging the kernel. It would be better to come up with a fix for silencing the noisy message in systemd, or configuring systemd to not attempt to attach filters to cgroups.

**Comment by anoo1** [comment]
Fix from Joel - https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-aspeed/+/12705/

**Comment by nest1ing** [comment]
If the `CONFIG_BPF_SYSCALL` is strongly required, we may add the `CONFIG_BPF_CGROUP` to the kernel to suppress the noisy messages.

Have any contraindications?

I tested it at our hardware and it looks fine.

**Comment by anoo1** [comment]
The kernel just grows slightly with the CONFIG_BPF_CGROUP option so seems like a viable solution:

Before:
```
-rw-r--r-- 2 anoo anoo 2581836 Sep 12 15:04 tmp/deploy/images/witherspoon/fitImage--4.18.7+git0+b7ba2a0af6-r0-witherspoon-20180912200202.bin
```
After:
```
-rw-r--r-- 2 anoo anoo 2582076 Sep 13 09:03 tmp/deploy/images/witherspoon/fitImage--4.18.7+git0+b7ba2a0af6-r0-witherspoon-20180913140208.bin
```

**Comment by shenki** [comment]
If we don't plan on using the feature we should not enable it simply to
suppress the log message.

To suppress the log message we should fix systemd to not output the message.

**Comment by nest1ing** [comment]
> Can we revert the kernel update that caused this until we can figure it out?

I've not found any broken things depended by this problem (but maybe I missed something). It just fills the system log with a lot of red and scare messages.

So, I guess, it is not critical and the revert is optional.
