### ISSUE TITLE
CONFIG_GCC_PLUGINS is not set in final .config

### ISSUE THREAD

**Issue by tomrepo** [openbmc/linux#170]
Per discussion with Andrew, let me open the issue for "GCC_PLUGINS not set" problem. Basically "CONFIG_GCC_PLUGINS" is enabled in meta-aspeed/recipes-kernel/linux/ast2500/defconfig, but it's disabled in the final .config file, and I think it's because its dependency option "PLUGIN_HOSTCC" is not set properly.

Below is "merge_config_build.log" (generated by "bitbake linux-aspeed" for romulus) which shows "CONFIG_GCC_PLUGINS" is not set in final .config.

Using .kernel-meta/configs//./defconfig as base
Merging .kernel-meta/configs//./romulus.cfg
Merging .kernel-meta/configs//./phosphor-gpio-keys.cfg
Merging .kernel-meta/configs//./phosphor-gpio-keys.cfg
Merging .kernel-meta/configs//./phosphor-vlan.cfg
Merging .kernel-meta/configs//./phosphor-vlan.cfg
Merging .kernel-meta/configs//./phosphor-wdt-on-panic.cfg
Value of CONFIG_PANIC_TIMEOUT is redefined by fragment .kernel-meta/configs//./phosphor-wdt-on-panic.cfg:
Previous value: CONFIG_PANIC_TIMEOUT=-1
New value: CONFIG_PANIC_TIMEOUT=0

Merging .kernel-meta/configs//./phosphor-wdt-on-panic.cfg
Merging .kernel-meta/configs//./phosphor-gpio-keys.cfg
Merging .kernel-meta/configs//./phosphor-vlan.cfg
make[1]: Entering directory `/data/users/taoren/lf-openbmc/openbmc/build/tmp/work/romulus-openbmc-linux-gnueabi/linux-aspeed/4.19.21+gitAUTOINC+d808d27f70-r0/linux-romulus-standard-build'
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --alldefconfig Kconfig

configuration written to .config

make[1]: Leaving directory `/data/users/taoren/lf-openbmc/openbmc/build/tmp/work/romulus-openbmc-linux-gnueabi/linux-aspeed/4.19.21+gitAUTOINC+d808d27f70-r0/linux-romulus-standard-build'
Value requested for CONFIG_GCC_PLUGINS not in final .config
Requested value:  CONFIG_GCC_PLUGINS=y
Actual value:

Value requested for CONFIG_NET_CADENCE not in final .config
Requested value:  # CONFIG_NET_CADENCE is not set
Actual value:

Value requested for CONFIG_INPUT_MOUSDEV not in final .config
Requested value:  # CONFIG_INPUT_MOUSDEV is not set
Actual value:

**Comment by shenki** [comment]
That's fine. We don't use any plugins currently.
