### ISSUE TITLE
ast2600: i3c support

### ISSUE THREAD

**Issue by ytmhub** [openbmc/linux#214]
Hi,

I was wondering if  i3c is supported in this kernel, or if any work is being done towards supporting it in the near future.

Regards,
Yotam

**Comment by shenki** [comment]
> Hi,
> 
> I was wondering if i3c is supported in this kernel, or if any work is being done towards supporting it in the near future.

Please use the mailing list for discussion:

openbmc@lists.ozlabs.org

No one has sent patches for I3C support yet.
