### ISSUE TITLE
How to configure for 'Video input from DVO' on OpenBMC?

### ISSUE THREAD

**Issue by MarkChuangGit** [openbmc/linux#215]
Hi,
Ast2500 support three video pathes
1. Video output
2. Graphics CRT output
3. Video input from DVO

I have a project which needs to use 'Video input from DVO'.
I follow ast2500 datasheet to modify SCU2C register and video function pins from -u-boot, but the KvM screen still is no display.

It seems like that there are some driver would modify SCU2C register.
Is there an example to do this feature for me to refer to?

**Comment by amboar** [comment]
You need use the pinctrl devicetree properties to enable the video capture pinmux state (VPI24 if I recall correctly): https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/pinctrl/aspeed,ast2500-pinctrl.yaml?h=v5.19#n66

However, issues are not the place to ask support questions. Please ask on the mailing list or on discord (preferably the mailing list)
