### ISSUE TITLE
 "iowait" high after 6.1.51 kernel

### ISSUE THREAD

**Issue by tichar** [openbmc/linux#224]
Found "iowait" to be very high on 6.1.51 kernel
After reverting the commit "f32dfc802e87 N - (9 months ago) io_uring: Use io_schedule* in cqring wait ", "iowait " drops to zero again.
There is a fix "c7920f992840 N - (9 months ago) io_uring: gate iowait schedule on having pending requests" on the community, but the actual verification does not work.

```
root@admin0001:~# top
Mem: 496008K used, 447808K free, 183516K shrd, 0K buff, 301600K cached
CPU:   0% usr  14% sys   0% nic   0% idle  85% io   0% irq   0% sirq
```

**Comment by williamspatrick** [comment]
OpenBMC hasn't used the 6.1.x kernel tree in over a year and we've never used 6.1.51.  Are you reporting this issue to the right place?
