### ISSUE TITLE
OCC driver is non-functional

### ISSUE THREAD

**Issue by nkskjames** [openbmc/linux#45]
Commit  087febae42dee3b389e995d958f5dd48a1f137a4 breaks the OCC hwmon driver.    root@barreleye:/sys/bus/i2c/devices/3-0050# echo 1 > online
occ-i2c 3-0050: ERROR: no SENSOR String in response
occ-i2c 3-0050: ERROR: cannot get occ sensor data: -1
-sh: echo: write error: Operation not permitted

If I don't apply this commit, the driver works fine:
 uname -r
4.3.4-fe68a785afbaa305506c87c6324f70ed0605385c

  ls /sys/class/hwmon
hwmon0  hwmon1  hwmon2  hwmon3  hwmon4

Looks to me like line 582 in drivers/hwmon/power8_occ_i2c.c should not have been removed.

**Comment by shenki** [comment]
Thanks for reporting this. I'm not getting notifications for this repository; can you make me an owner so I get that?

The line was removed as I have further cleanup patches for the occ driver that aren't ready yet. Thanks for fixing it; it's in the tree as https://github.com/openbmc/linux/commit/2a3f5f14fdf2e8fb680af168fa642ef8a9218ffb
