### ISSUE TITLE
kernel unable to access tmp421 and ds1307

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/linux#96]
@bradbishop commented on [Wed Jun 29 2016](https://github.com/openbmc/u-boot/issues/12)

Similar to https://github.com/openbmc/u-boot/issues/11, this seems to be a hangup for the kernel due to the move from 2013.07 to 2016.05.

On bmc boot the rtc and tmp421 sensor cannot be accessed:

rtc-ds1307: probe of 0-0068 failed with error -5
tmp421 2-004c: Could not read configuration register (-5)
tmp421: probe of 2-004c failed with error -5

---

@shenki commented on [Thu Jun 30 2016](https://github.com/openbmc/u-boot/issues/12#issuecomment-229580655)

Thanks for testing. I assume this is on Palmetto as well? Can you reproduce in Qemu?

We want these opened as kernel issues. We need the kernel handle poorly configured hardware.

---

@legoater commented on [Thu Jun 30 2016](https://github.com/openbmc/u-boot/issues/12#issuecomment-229614042)

The previous u-boot was adding an I2C driver which was doing a reset of the I2C controller. 

Should we add such a reset in the machine setup in the kernel  ? 

---

@williamspatrick commented on [Thu Jul 14 2016](https://github.com/openbmc/u-boot/issues/12#issuecomment-232702520)

@shenki - Do you want this moved to kernel?  You can move it with 'zenhub' (or I can do it for you).

---

@shenki commented on [Tue Jul 19 2016](https://github.com/openbmc/u-boot/issues/12#issuecomment-233622337)

Yes, lets move this to the kernel

**Comment by shenki** [comment]
This has been resolved with the move to dev-4.7
